package cn.lypi.transport.tui;

public enum TerminalInputAction {
    CLEAR_INPUT,
    INTERRUPT,
    SUBMIT_PERMISSION_OPTION,
    INSERT_PASTE,
    INSERT_NEWLINE,
    DELETE_PREVIOUS_WORD,
    DELETE_NEXT_WORD,
    MOVE_WORD_LEFT,
    MOVE_WORD_RIGHT,
    PREVIOUS_HISTORY,
    NEXT_HISTORY,
    TOGGLE_THINKING,
    EXPAND_TOOLS,
    RESTORE_FOCUS,
    EXIT,
    NOOP
}
